import { Router, Request, Response } from 'express';
import { prisma } from '../../lib/prisma';
import { authenticateToken } from '../../middleware/auth';
import { KIND_BY_PARAM, ConnectorDefinition } from '../../connector/definition.types';
import { runResource } from '../../connector/engine';
import { encryptSecrets, decryptSecrets, maskSecrets, getKey } from '../../connector/engine/secrets';
export { validateDefinition, requiredParams } from '../../connector/definition.schema';
import { validateDefinition, requiredParams } from '../../connector/definition.schema';

function decrypt(blob: Buffer): Record<string, string> {
  return decryptSecrets(blob, getKey());
}

// Prisma's generated Bytes field type is strict about the ArrayBuffer generic;
// Buffer (Node >=20 typings) is backed by ArrayBufferLike (includes SharedArrayBuffer),
// so a narrowing cast is needed at the write boundary.
function toBytes(buf: Buffer): Uint8Array<ArrayBuffer> {
  return buf as unknown as Uint8Array<ArrayBuffer>;
}

function resolveKind(req: Request, res: Response): 'LINE' | 'STOP' | 'DIRECTION' | 'NEXTPASSAGE' | null {
  const kind = KIND_BY_PARAM[req.params.kind];
  if (!kind) { res.status(404).json({ error: `Unknown resource: ${req.params.kind}` }); return null; }
  return kind;
}

async function loadResource(connectorId: string, kind: any) {
  return prisma.connectorResource.findUnique({ where: { connectorId_kind: { connectorId, kind } } });
}

async function assertOwner(req: Request, res: Response): Promise<boolean> {
  const owned = await prisma.connector.findFirst({
    where: { id: req.params.connectorId, userId: req.user!.id },
    select: { id: true },
  });
  if (!owned) { res.status(404).json({ error: 'Connector not found' }); return false; }
  return true;
}

export function createConnectorResourceRouter(): Router {
  const router = Router({ mergeParams: true });

  // GET config (back-compat: exposes params + masked secrets)
  router.get('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    if (!(await assertOwner(req, res))) return;
    const row = await loadResource(req.params.connectorId, kind);
    if (!row) return res.status(404).json({ error: 'Resource not found' });
    res.json({
      id: row.id, connectorId: row.connectorId, kind: row.kind, name: row.name,
      definition: row.definition,
      params: requiredParams(row.definition as unknown as ConnectorDefinition),
      secrets: row.secrets ? maskSecrets(row.secrets as Buffer, getKey()) : {},
    });
  });

  // Upsert config
  router.patch('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    if (!(await assertOwner(req, res))) return;
    const { name, definition, secrets } = req.body;
    const errors = validateDefinition(definition);
    if (errors.length) return res.status(422).json({ errors });

    const existingRow = await loadResource(req.params.connectorId, kind);
    let secretsBytes: Uint8Array<ArrayBuffer> | null | undefined = undefined; // undefined = leave unchanged
    if (secrets !== undefined) {
      const merged: Record<string, string> = existingRow?.secrets ? decrypt(existingRow.secrets as Buffer) : {};
      for (const [k, v] of Object.entries(secrets as Record<string, string | null>)) {
        if (v === null) delete merged[k];
        else merged[k] = v;
      }
      secretsBytes = Object.keys(merged).length ? toBytes(encryptSecrets(merged, getKey())) : null;
    }

    const row = await prisma.connectorResource.upsert({
      where: { connectorId_kind: { connectorId: req.params.connectorId, kind } },
      update: { name, definition, ...(secretsBytes !== undefined ? { secrets: secretsBytes } : {}) },
      create: { connectorId: req.params.connectorId, kind, name: name ?? '', definition, secrets: secretsBytes ?? undefined },
    });
    res.json({ id: row.id, kind: row.kind, name: row.name });
  });

  router.delete('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    if (!(await assertOwner(req, res))) return;
    await prisma.connectorResource.delete({ where: { connectorId_kind: { connectorId: req.params.connectorId, kind } } });
    res.json({ ok: true });
  });

  // Preview / dry-run (authenticated). Accepts an inline definition + secrets so
  // the back-office can test unsaved edits (and connectors not yet saved).
  router.post('/:kind/preview', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    if (!(await assertOwner(req, res))) return;
    const row = await loadResource(req.params.connectorId, kind);
    const definition = (req.body.definition ?? row?.definition) as ConnectorDefinition | undefined;
    if (!definition) return res.status(404).json({ error: 'No definition to preview' });
    if (req.body.definition) {
      const errors = validateDefinition(req.body.definition);
      if (errors.length) return res.status(422).json({ errors });
    }
    const stored = row?.secrets ? decrypt(row.secrets as Buffer) : {};
    const secrets = { ...stored, ...(req.body.secrets ?? {}) };
    const result = await runResource(definition, kind, {
      params: req.body.params ?? {},
      page: req.body.page,
      secrets,
      sampleResponse: req.body.sampleResponse,
    });
    res.json({ ok: result.ok, stage: result.stage, message: result.message, raw: result.raw, envelope: result.envelope, diagnostics: result.diagnostics });
  });

  // Proxy (unauthenticated for mobile back-compat; SSRF-guarded in fetch)
  router.get('/:kind/proxy', async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    const row = await loadResource(req.params.connectorId, kind);
    if (!row) return res.status(404).json({ error: 'Resource not found' });
    const secrets = row.secrets ? decrypt(row.secrets as Buffer) : {};
    const page = {
      offset: req.query.offset !== undefined ? Number(req.query.offset) : undefined,
      page: req.query.page !== undefined ? Number(req.query.page) : undefined,
      cursor: req.query.cursor as string | undefined,
    };
    const result = await runResource(row.definition as unknown as ConnectorDefinition, kind, {
      params: req.query as Record<string, any>, page, secrets,
    });
    if (!result.ok && result.stage && result.stage !== 'validate') {
      return res.status(result.stage === 'fetch' ? 502 : 400).json({ error: result.message, stage: result.stage });
    }
    res.json(result.envelope);
  });

  return router;
}
