import { Router, Request, Response } from 'express';
import { prisma } from '../../lib/prisma';
import { authenticateToken } from '../../middleware/auth';
import { KIND_BY_PARAM, ConnectorDefinition } from '../../connector/definition.types';
import { runResource } from '../../connector/engine';
import { encryptSecrets, decryptSecrets, maskSecrets, getKey } from '../../connector/engine/secrets';
export { validateDefinition, requiredParams } from '../../connector/definition.schema';
import { validateDefinition, requiredParams } from '../../connector/definition.schema';

function decrypt(blob: Buffer): Record<string, string> {
  return decryptSecrets(blob, getKey());
}

// Prisma's generated Bytes field type is strict about the ArrayBuffer generic;
// Buffer (Node >=20 typings) is backed by ArrayBufferLike (includes SharedArrayBuffer),
// so a narrowing cast is needed at the write boundary.
function toBytes(buf: Buffer): Uint8Array<ArrayBuffer> {
  return buf as unknown as Uint8Array<ArrayBuffer>;
}

function resolveKind(req: Request, res: Response): 'LINE' | 'STOP' | 'DIRECTION' | 'NEXTPASSAGE' | null {
  const kind = KIND_BY_PARAM[req.params.kind];
  if (!kind) { res.status(404).json({ error: `Unknown resource: ${req.params.kind}` }); return null; }
  return kind;
}

async function loadResource(connectorId: string, kind: any) {
  return prisma.connectorResource.findUnique({ where: { connectorId_kind: { connectorId, kind } } });
}

export function createConnectorResourceRouter(): Router {
  const router = Router({ mergeParams: true });

  // GET config (back-compat: exposes params + masked secrets)
  router.get('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    const row = await loadResource(req.params.connectorId, kind);
    if (!row) return res.status(404).json({ error: 'Resource not found' });
    res.json({
      id: row.id, connectorId: row.connectorId, kind: row.kind, name: row.name,
      definition: row.definition,
      params: requiredParams(row.definition as unknown as ConnectorDefinition),
      secrets: maskSecrets(row.secrets as Buffer | null, getKey()),
    });
  });

  // Upsert config
  router.patch('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    const { name, definition, secrets } = req.body;
    const errors = validateDefinition(definition);
    if (errors.length) return res.status(422).json({ errors });

    const encrypted = secrets && Object.keys(secrets).length ? encryptSecrets(secrets, getKey()) : undefined;
    const row = await prisma.connectorResource.upsert({
      where: { connectorId_kind: { connectorId: req.params.connectorId, kind } },
      update: { name, definition, ...(encrypted ? { secrets: toBytes(encrypted) } : {}) },
      create: { connectorId: req.params.connectorId, kind, name: name ?? '', definition, secrets: encrypted ? toBytes(encrypted) : undefined },
    });
    res.json({ id: row.id, kind: row.kind, name: row.name });
  });

  router.delete('/:kind', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    await prisma.connectorResource.delete({ where: { connectorId_kind: { connectorId: req.params.connectorId, kind } } });
    res.json({ ok: true });
  });

  // Preview / dry-run (authenticated)
  router.post('/:kind/preview', authenticateToken, async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    const row = await loadResource(req.params.connectorId, kind);
    if (!row) return res.status(404).json({ error: 'Resource not found' });
    const secrets = row.secrets ? decrypt(row.secrets as Buffer) : {};
    const result = await runResource(row.definition as unknown as ConnectorDefinition, kind, {
      params: req.body.params ?? {},
      page: req.body.page,
      secrets,
      sampleResponse: req.body.sampleResponse,
    });
    res.json({ ok: result.ok, stage: result.stage, message: result.message, raw: result.raw, envelope: result.envelope, diagnostics: result.diagnostics });
  });

  // Proxy (unauthenticated for mobile back-compat; SSRF-guarded in fetch)
  router.get('/:kind/proxy', async (req: Request, res: Response) => {
    const kind = resolveKind(req, res); if (!kind) return;
    const row = await loadResource(req.params.connectorId, kind);
    if (!row) return res.status(404).json({ error: 'Resource not found' });
    const secrets = row.secrets ? decrypt(row.secrets as Buffer) : {};
    const page = {
      offset: req.query.offset !== undefined ? Number(req.query.offset) : undefined,
      page: req.query.page !== undefined ? Number(req.query.page) : undefined,
      cursor: req.query.cursor as string | undefined,
    };
    const result = await runResource(row.definition as unknown as ConnectorDefinition, kind, {
      params: req.query as Record<string, any>, page, secrets,
    });
    if (!result.ok && result.stage && result.stage !== 'validate') {
      return res.status(result.stage === 'fetch' ? 502 : 400).json({ error: result.message, stage: result.stage });
    }
    res.json(result.envelope);
  });

  return router;
}
